### PR TITLE
cpp11 error solved

### PR DESCRIPTION
**Pull request by gerkovink**
Added cpp11 link to DESCRIPTION. 

Solves issue #286

### CODE REVIEW

**Comment by gerkovink** [comment]
Build check:

```r
── R CMD check results ─────────────────────────────── mice 3.12.0 ────
Duration: 4m 6s

0 errors ✓ | 0 warnings ✓ | 0 notes ✓

R CMD check succeeded
```

**Comment by stefvanbuuren** [comment]
Thanks. Now merged. Could you check?

**Comment by gerkovink** [comment]
All good now!

``` r
devtools::install_github("amices/mice")
#> Downloading GitHub repo amices/mice@HEAD
#> 
#>      checking for file ‘/private/var/folders/j6/w513cp9s071c3zfcwl_btn_r0000gn/T/Rtmpl7AR7v/remotes1060e4052ac04/amices-mice-50cee45/DESCRIPTION’ ...  ✓  checking for file ‘/private/var/folders/j6/w513cp9s071c3zfcwl_btn_r0000gn/T/Rtmpl7AR7v/remotes1060e4052ac04/amices-mice-50cee45/DESCRIPTION’
#>   ─  preparing ‘mice’: (797ms)
#>      checking DESCRIPTION meta-information ...  ✓  checking DESCRIPTION meta-information
#>   ─  cleaning src
#>   ─  checking for LF line-endings in source and make files and shell scripts (562ms)
#>   ─  checking for empty or unneeded directories
#>      Removed empty directory ‘mice/vignettes’
#>   ─  building ‘mice_3.12.0.tar.gz’
#>      
#> 
```

<sup>Created on 2020-11-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Review by stefvanbuuren — COMMENTED** [review]
ok

**Pull request merged**
