### PR TITLE
Add Jamshidian & Jalal's 2010 non-parametric MCAR test 

### PR DESCRIPTION
**Pull request by cjvanlissa**
As discussed with @gerkovink

### CODE REVIEW

**Comment by gerkovink** [comment]
Thanks @cjvanlissa. 

@stefvanbuuren Although I am not a fan of MCAR tests, I believe it does serve some of our users if we offer a test that aims to identify MCAR *given that the data are at least MAR*

**Comment by cjvanlissa** [comment]
@gerkovink @stefvanbuuren the documentation and print method of the test also emphasize that a non-significant MCAR test does not distinguish between MCAR or MNAR, and that a significant one is indicative of MAR. I believe this to be the correct interpretation based on the literature cited in the function documentation

**Comment by stefvanbuuren** [comment]
Thanks Caspar. I think this is a useful addition to `mice`. 

In order to make your contribution mergeable, could you please address the following points:

- Running `res <- MCAR(nhanes)` produces a warning `Warning message: In MCAR.data.frame(nhanes) : Some columns contain less than five unique values. Be advised that this test has not been validated for categorical variables.` The warning does not seem appropriate here since `nhanes` contains only numerical data. The convention is `mice` is that categorical data are factors, and hence the warning may confuse readers.
- Running `res <- MCAR(nhanes2)` gives `Error in MCAR.data.frame(nhanes2) : Imputed data contain missing values.`. This is a puzzling error since `nhanes` also contains missing data, but did not error. Please rephrase as something like: "Sorry, the test cannot be applied to (ordered) factors."
- Running `res <- MCAR(nhanes, min_n = 0)` produces `Error in MCAR.data.frame(nhanes, min_n = 0) : object 'idpats' not found`. It is better to inform the user that `min_0` should be at least 1, and then stop gracefully. Please add the requirement to the documentation of the `min_n` argument.
- Documentation is unclear: "Jamshidian and Jalal's non-parametric MCAR test assumes that, if data are not MAR, the covariance matrices of the imputed data will be equal accross groups with different patterns of missingness. This assumption is tested using the following procedure:". Perhaps rephrase as something like: "Jamshidian and Jalal's non-parametric MCAR test assumes that the missing data are either MCAR or MAR, and tests whether the missingness is independent of the observed values. If so, the covariance matrices of the imputed data will be equal accross groups with different patterns of missingness. This test consists of the following procedure:"
- Documentation is unclear: "Note that, despite its name in common parlance, an MCAR test can only indicate whether missingness is MAR versus non-MAR. A non-significant MCAR test cannot distinguish between MCAR or MNAR. Perhaps rephrase as: "Note that, despite its name in common parlance, an MCAR test can only indicate whether missingness is MCAR or MAR. The procedure cannot distinguish MCAR from MNAR, so a non-significant result does not rule our MNAR."
- The `[ctb]` addition after the author produces a warning, so please remove.
- In `R/import.R` add imports to `hist` and `dev.off`. Add `grDevices` to `Imports: ` section in DESCRIPTION. 
- Put `person("Caspar", "van Lissa", role = "ctb", email = "c.j.vanlissa@uu.nl")` after the Ian White entry in DESCRIPTION.
- Please provide a bullet point text in `NEWS.md` annoucing your contribution.

**Review by stefvanbuuren — CHANGES_REQUESTED** [review]
See separate comments

**Comment by cjvanlissa** [comment]
@stefvanbuuren sorry this took so long; I believe your comments should be addressed now!

**Comment by stefvanbuuren** [comment]
Thanks for your contribution Caspar. 

Seems to need `decor`, so I'll add that to suggests.

**Comment by stefvanbuuren** [comment]
I will rename `MCAR()`  to `mcar()`, which better suits the mice function name style.

**Comment by cjvanlissa** [comment]
@stefvanbuuren looks good! I'm pretty sure `decor` is not a direct dependency of my code, but more likely a new dependency of `Rcpp` or something.

**Pull request merged**
