### PR TITLE
Add plotting functionality for new ignore paramter

### PR DESCRIPTION
**Pull request by prockenschaub**
## Scope 

1328a61 and #266 propose a new `ignore` parameter that allows users to specify rows in the data that are ignored during imputation model training (but which are imputed after the imputation model was trained). Currently, out-of-the-box plotting methods in `mice` do not support this parameter and treat all imputations in the same way. This PR tries to adapt the plotting functions in `mice` to allow for better diagnostic plots in use cases that include `ignore`.

## Progress

- [ ] `plot`: convergence plot across iterations (mean and sd)
- [ ] `stripplot`: one-dimensional scatterplots for observed and imputed data
- [ ] `xyplot`: two-dimensional scatterplots for observed and imputed data
- [ ] `bwplot`: box-and-whiskers plots for observed and imputed data

### CODE REVIEW

**Comment by prockenschaub** [comment]
@stefvanbuuren @gerkovink  This PR is currently an exact clone of #269 which I added mainly for discussions on the plotting functionality. I started thinking about the plots and wanted to raise a few questions before fully embarking on it:

1. Doe the above cover all of the relevant plots in `mice`?
2. `plot` uses the stored `chainMean` and `chainVar` in the `mids` object to plot convergence. In my mind, these means should be separately calculated for observations included in the imputation model building (i.e. `ignore == FALSE`) and observations omitted from model building (but still imputed, i.e. `ignore == TRUE`). This would require a second set of means and vars in the `mids` object, so this would be a relatively large change to a core component of `mice`. It is also relevant for `filter.mids` #269 , which currently throws away means and vars since it is unable to recalculate the means and vars of the filtered subset. Do think this is necessary, or would you rather not make such a change? Are there any hidden pitfalls that I am not aware of?
3. For all the other plots, I think the most sensible thing to do would be to include a third colour for observations that were ignored. This allows users to visually inspect whether imputations for ignored observations differ from those that were included. Do you agree with that notion?

**Comment by gerkovink** [comment]
@prockenschaub Thanks. 

1. Those are the core plotting functions. @hanneoberman Can you chime in with some info on your new plots cf. `ggplot2` and `plotly`, if relevant?
2. I agree. @hanneoberman Since it considers plotting parameters over the iterations, would you mind giving your 2 cents?
3. Agreed. A new color should then be defined in `mice.theme.R`. @stefvanbuuren do you have a suggestion for a colour that would get along with the colours in FIMD?

**Comment by hanneoberman** [comment]
@prockenschaub @gerkovink 
1. I still miss `densityplot` in this list (maybe not considered a core plotting function? `fluxplot` is not relevant here). 
The new plotting functions I'm developing are meant to be `ggplot2` 'siblings' for the current `lattice` plots. They are not 100% identical but made to be very similar. One advantage of `ggplot2` objects over the current implementation is that adjusting the data is possible after creating the plotting object. This means that users can filter the data post hoc, and add custom colors themselves. The code (under development!) is available on the `shinymice` repo, https://github.com/amices/shinyMice/tree/master/R, in the `gg.[plotname].R` files.
2. I am not familiar enough with the filtering options to give a meaningful response. I genuinely do not know whether convergence would be different for observations that are not included in the modeling step. Since chain means and chain variances are aggregate parameters, they only tell us something about the overall trend in imputed values. A sort of 'sensitivity analysis' to investigate the effect of a (set of) observation(s) may be interesting, but not necessary IMO.
3. I wasn't asked, but I'd use grey.

**Comment by stefvanbuuren** [comment]
Ah sorry, I already merged this PR by accident. Still need to take a look.

**Comment by stefvanbuuren** [comment]
Thanks to you all.

1. We should also cover `densityplot()` indeed.
2. I agree that it would be better to have separate calculations depending on `ignore`. However, for now, I am inclined to leave things as they are for `plot()` for the following reasons: 
a. The current code that calculates means and variances by iteration is unelegant, and it would become even more murky if we try to fit in an extra layer;
b. It means a change in de `mids` object, and there might be consequences for backward compatibility;
c.  I would like to extend `mice()` with a (user-specified) function that runs after every complete iteration. This is a larger project in itself.
As a quick fix: It is possible to do a poor-man's version by repeated calling `mice.mids()` with one iteration, and stuff any code in between calls. Section 9.4.3 of my book shows how to calculate Kendall's $\tau$ at every iteration.
3. We currently have blue = observed, red = missing/imputed, grey = combined (used sparingly). Suppose that we use these colours for the active rows. Shouldn't we then need two additional colours, for ignored-observed and ignored-imputed? An alternative is to double the number of panels and make side-by-side plots for training-test pairs. This is relatively straightforward for all four lattice plots in the package, and could perhaps already be done with the current lattice formula interface. Also, extending to a third set should then be easy. What about that option?

**Comment by stefvanbuuren** [comment]
Since this PR is merged, it moved to the closed list. I do not seem capable of re-opening. 
@prockenschaub Can you re-open?

**Comment by prockenschaub** [comment]
I don't think reopening a merged PR is possible without undoing the commits. I will have a close look at all your suggestions and will start working on this this week, opening a new PR that links to this one.

**Pull request merged**
