### PR TITLE
Update futuremice

### PR DESCRIPTION
**Pull request by thomvolker**
Implements the following changes:
- Allow for user-specified functions or the use of auxiliary packages within futuremice.
- Initialize random seed of this has not happened before.
- Add function for core checking and use smarter n.core specification

### CODE REVIEW

**Comment by thomvolker** [comment]
This pull request would solve #139, #529, #533 and #544. Additionally, #542 can be closed as per the regular `futuremice()` functionality.

**Comment by gerkovink** [comment]
@thomvolker do the checks pass on your machine?

**Comment by gerkovink** [comment]
I meant the windows one, not the Unix ones. I'll rebuild and rerun the checks

**Comment by thomvolker** [comment]
Thanks! I now see that the checks also didn't pass after @stefvanbuuren's latest update (see https://github.com/amices/mice/actions/runs/3673696826).

**Comment by stefvanbuuren** [comment]
I just updated the GitHub action script. `mice 3.15.2` now gets its five green balls.

**Comment by stefvanbuuren** [comment]
Yes. Please incorporate the changes of mice 3.15.2. Do not increase the version number in the PR as I want to restrict version increases to the master. So put your news above the 3.15.2 news and after merge I will create v3.15.+.

**Comment by thomvolker** [comment]
Then I think everything is now set, but let me know if there are other changes that have to be made first.

**Pull request merged**
